### ISSUE TITLE
A way to clear the queue?

### ISSUE THREAD

**Issue by rmcmullanLB** [rmick/LTTO_Library#4]
Is there a way to clear the queue of received signals?  I'm designing a target shooting game where it sits in non-scoring mode for 5 seconds, changes to scoring mode for 2 seconds, and then returns to non-scoring mode.  However I notice that if I shoot it during non-scoring mode, as soon as scoring mode runs ltto.available() it finds the tag launched during non-scoring mode.  Is there a way to flush the queue or turn off receiving?  I'm still learning the inner functionings of this wonderful library.

**Comment by rmick** [comment]
No there is not any method to clear the message queue.

I had not thought of this scenario. Give me a week or two and I will add one in for you.

**Comment by rmick** [comment]
Done. As you can see flattery will get you everywhere :-)

There is a new method you can call.

void  LTTO::clearIRmessage()
{
    decodedIRmessage.newMessage     = false;
    decodedIRmessage.type           = NO_MESSAGE;
    decodedIRmessage.rawDataPacket  = 0;
}

As you can see it sets the newMessage to false and the type to NO_MESSAGE.
It leaves all the other data intact, but this should be enough to stop your code looking any further.

Good luck with your game.
